:recycle: refactor: add default_nick_name table and get random nickname
depromeet/street-drop-server pull request #147
Opened 2023-06-28 13:31 UTC by seonghun-dev

resolve : https://github.com/depromeet/street-drop-server/issues/148

2023-07-02 12:00 UTC, siyeonSon approved these changes
고생하셨습니당 👍

2023-07-03 07:16 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/DefaultNickName.java
> +        private String postNickName;
저희 닉네임 최대 10글자까지 아니였나요??

2023-07-03 07:16 UTC, yunyoung1819 requested changes
Good!

2023-07-07 11:42 UTC, seonghun-dev commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/DefaultNickName.java
> +        private String postNickName;
확인해보니 10글자이군요. 수정해두겠습니다

2023-07-08 10:15 UTC, merged