:sparkles: feat: add banned word when create item
depromeet/street-drop-server pull request #160
Opened 2023-06-29 14:27 UTC by seonghun-dev

Resolve : https://github.com/depromeet/street-drop-server/issues/159

2023-07-02 12:09 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/common/repository/BannedWordRepository.java
> +    List<String> findBannedWordsInWordList(@Param("words") List<String> words);
`LIMIT 1`인데 `List<String>`으로 반환하는 것보다 `String`으로 반환해도 좋을 것 같아요

2023-07-03 06:45 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemService.java
> +        var bannedWord = bannedWordRepository.findBannedWordsInWordList(contentWord);
List이기 때문에 contentWords, bannedWords 처럼 복수형이 조금 더 좋지 않나여?

2023-07-03 06:58 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemService.java
> +        }
checkBannedWord 같은 별도 private 메서드로 추출해도 좋을 것 같습니다.

2023-07-03 07:08 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/common/repository/BannedWordRepository.java
> +    @Query("SELECT bw.word FROM BannedWord bw WHERE bw.word IN :words LIMIT 1")
LIMIT 1 좋은 것 같습니다 👍

2023-07-03 07:13 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemService.java
> +        var bannedWord = bannedWordRepository.findBannedWordsInWordList(contentWord);
지금은 아이템 코멘트쪽에만 금칙어가 쓰이니까 이렇게 구현하고, 나중에는 댓글 작성시에도 금칙어 필터링이 들어가야 하니까 추후 AOP를 이용해 애노테이션으로 만들어서 비즈니스 로직이랑 분리해보는 것도 전 괜찮을 것 같은데 어떠실까요?

2023-07-03 07:13 UTC, yunyoung1819 requested changes
Good

2023-07-07 11:41 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemService.java
> +        var bannedWord = bannedWordRepository.findBannedWordsInWordList(contentWord);
댓글이랑 닉네임에도 적용되는 것이 좋을 것 같네요 수정해보겠습니다

2023-07-07 11:42 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemService.java
> +        }
외부 AOP 형태로 사용가능하도록 빼두겠습니다

2023-07-11 15:04 UTC, seonghun-dev commented
@yunyoung1819 
@siyeonSon 
IOS 배포 후 최초 업데이트에 적용 예정입니다.

2023-09-06 15:43 UTC, DongGeon0908 reviewed
놀러왔어요! 이 서비스 너무 좋아용~

2023-09-06 15:43 UTC, DongGeon0908 commented on backend/streetdrop-api/src/main/java/com/depromeet/common/repository/BannedWordRepository.java
> +    @Query("SELECT bw.word FROM BannedWord bw WHERE bw.word IN :words LIMIT 1")
@yunyoung1819 @seonghun-dev 

Limit 1이면 한건 조회하는 쿼리 같은데.. List가 아니지 않나요????
무조건 1건이면 반환 값이 String으로 가져가야 하는게 맞지 않을까..

2023-09-10 16:52 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/common/repository/BannedWordRepository.java
> +    @Query("SELECT bw.word FROM BannedWord bw WHERE bw.word IN :words LIMIT 1")
놓쳤군요 감사합니다

2023-09-16 13:08 UTC, seonghun-dev commented
@siyeonSon @yunyoung1819 
AOP 형태로 사용가능하도록 수정했습니다. 시간나실때 리뷰 부탁드립니다

2023-09-23 07:08 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/common/annotation/NotBannedWord.java
> +}
annotation 이나 util 클래스들은 streetdrop-common 모듈에 두기로 했는데, common 모듈로 이동시키는 건 어떤가요?
예를 들어 admin에서 관리자가 임의로 데이터를 생성/수정 할 때 활용할 수 있을 것 같아요!

2023-09-23 07:18 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/common/repository/BannedWordRepository.java
> +    List<String> findBannedWordsInWordList(@Param("words") List<String> words);
banned word가 여러 개인 경우도 있을 것 같아요! 단어 1개를 반환하는 대신에 여러 개를 반환하는 건 어떤가요?

2023-09-23 07:18 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/common/repository/BannedWordRepository.java
> +    List<String> findBannedWordsInWordList(@Param("words") List<String> words);
현재 단어 1개를 반환하는데, 리턴 값과 메서드 명이 수정되어야 할 것 같아요! 

```suggestion
    @Query("SELECT bw.word FROM BannedWord bw WHERE bw.word IN :words")
    String findBannedWordsInWord(@Param("words") List<String> words);
```

2023-09-23 07:47 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/common/annotation/NotBannedWord.java
> +}
이 부분이 데이터 베이스의 데이터를 의존하고 있어서 이동하게 되면 common 모듈의 복잡성이 늘어날 것 같습니다

2023-09-23 07:54 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/common/annotation/NotBannedWord.java
> +}
좋아요~

2023-09-23 08:06 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/common/annotation/validator/BannedWordValidator.java
> +        var contentWord = List.of(value.split(" "));
단어가 List이니까 변수명이 contentWords 복수형이 좀 더 적절한 것 같습니당

2023-09-23 08:08 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/common/entity/BannedWord.java
> +@NoArgsConstructor
접근 범위는 최소화하는 것이 좋기 때문에
@NoArgsConstructor(access = PROTECTED) 이렇게 PROTECTED로 변경하면 어떨까요~?

2023-10-09 11:30 UTC, yunyoung1819 approved these changes
테스트 코드 충돌난 것 수정되시면 머지해주셔도 될 것 같습니다. 고생 많으셨습니다 (Good)

2023-10-25 05:36 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/common/annotation/validator/BannedWordValidator.java
> +        var contentWord = List.of(value.split(" "));
수정했습니다

2023-10-25 05:37 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/common/repository/BannedWordRepository.java
> +    List<String> findBannedWordsInWordList(@Param("words") List<String> words);
IN 으로 여러개가 반환될 수 되있어서 List로 처리하고 있습니다

2023-10-25 06:55 UTC, seonghun-dev commented on backend/streetdrop-domain/src/main/java/com/depromeet/common/entity/BannedWord.java
> +@NoArgsConstructor
수정했습니다

2023-10-25 07:50 UTC, merged