:sparkles: add nickname change api
depromeet/street-drop-server pull request #162
Opened 2023-06-30 02:26 UTC by yunyoung1819

Resolve: #158

2023-07-01 07:02 UTC, seonghun-dev requested changes

2023-07-03 03:28 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserController.java
> +    @PatchMapping("/nickname")
좋은 것 같습니다. 
반영했습니다.

2023-07-03 03:31 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserController.java
> +            @RequestParam("nickname") @Size(min = 1, max = 10) String nickname
좋은 것 같습니다.
반영했습니다. 👍

2023-07-03 03:35 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserService.java
> +		var findUser = userRepository.findUserByIdfv(user.getIdfv())
넵 처음에는

```
var findUser = userRepository.findUserByIdfv(user.getIdfv())
     .orElseThrow(() -> new NotFoundException(ErrorCode.NOT_FOUND, user.getId()));
findUser.changeNickname(nickname);
```
이렇게 조회와 변경을 분리했어서 findUser로 명명했는데, 지금은 changedUser가 좀 더 좋은 것 같습니다.
반영했습니다.

2023-07-03 03:43 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserService.java
> +	private void validateNicknameLength(String nickname) {
음 처음에 `@Size`는 컨트롤러 파라미터 검증 단계에서 체크하고, ValidationNickname은 
서비스 계층에서 테스트 및 재사용할 수 있는 용도로 만들어두려고 생각했었는데
지금 보니 두번 처리할 필요는 없을 것 같습니다. 
반영했습니다.

2023-07-03 05:06 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserService.java
> +		var findUser = userRepository.findUserByIdfv(user.getIdfv())
음 find를 한번 더 안한다는 점에서 성능상으로 위의 방식이 좀더 좋으려나요?

2023-07-03 09:38 UTC, siyeonSon approved these changes
👍👍👍

2023-07-03 14:29 UTC, merged