:bug: fix return value of user.getMusicApp() is null
depromeet/street-drop-server pull request #170
Opened 2023-07-04 14:30 UTC by yunyoung1819

Resolve: #169

2023-07-05 10:12 UTC, siyeonSon reviewed
unit 테스트할 때 실패 뜨는데 확인부탁 드립니당

2023-07-07 10:41 UTC, seonghun-dev requested changes

2023-07-07 10:41 UTC, seonghun-dev commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
> +		if (musicApp == null) {
가져올때 확인할 필요가 없이 default로 지정하고 dml로 현재 에러 해결하면 되지 않나요?

2023-07-07 13:55 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
> +		if (musicApp == null) {
넵 반영했습니다.

2023-07-08 05:21 UTC, yunyoung1819 commented
> unit 테스트할 때 실패 뜨는데 확인부탁 드립니당

넵 수정했습니다.

2023-07-08 06:16 UTC, siyeonSon approved these changes

2023-07-08 06:29 UTC, seonghun-dev commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/vo/MusicApp.java
> +		if (appName == null) {
appName이 enum으로 되어있는데 null처리를 할 필요가 있을까요?

2023-07-10 09:38 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/vo/MusicApp.java
> +		if (appName == null) {
기존 DB에 null로 되어있어서 추가했었는데 DML로 작업하고 해당 부분은 수정했습니다.

2023-07-10 09:40 UTC, merged