:sparkles: feat(api, domain): Add user level get API
depromeet/street-drop-server pull request #218
Opened 2023-07-15 10:36 UTC by yunyoung1819

- Resolve: #217

2023-07-15 11:17 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +		Optional<UserLevel> userLevel = userLevelRepository.findLevelByUserId(user.getId());
.orElse();
-> 기본 레벨값으로 지정

2023-07-15 11:17 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +	private final AwsS3Service awss3Service;
생성 부분은 어드민이나 sql로 처리가 가능할 것 같습니다

2023-07-15 11:17 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/aws/s3/AwsS3Service.java
> +public class AwsS3Service {
추가 pr로 나뉘어서 바로 올려주시면 좋을 것 같습니다

2023-07-15 11:17 UTC, seonghun-dev commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/UserLevel.java
> +public class UserLevel {
UserLevel 제외하고 User에 Level 정보만 들어갈 것 같습니다

2023-07-15 11:17 UTC, seonghun-dev commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/vo/Level.java
> +public enum Level {
테이블로 관리되면 좋을 것 같습니다

2023-07-15 11:22 UTC, siyeonSon commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/vo/Level.java
> +public enum Level {
User : UserLevel의 관계는 1 : N
연관관계 주인은 User

2023-07-15 11:34 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +		Optional<UserLevel> userLevel = userLevelRepository.findLevelByUserId(user.getId());
UserLevel userLevel = userLevelRepository.findLevelByUserId(user.getId()).orElse(
 // UserLevel 객체
);

2023-07-15 12:11 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/external/aws/s3/AwsS3Service.java
> +public class AwsS3Service {
넵 추가 PR로 올렸습니다 Good!

2023-07-15 13:09 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/external/aws/s3/AwsS3Service.java
> +		return DIR_NAME + "/" + "Level1.png";
따로 수정해서 PR 올렸습니다. Good!

2023-07-15 17:52 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/vo/Level.java
> +public enum Level {
넵 수정했습니다.

2023-07-15 17:53 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/UserLevel.java
> +public class UserLevel {
넵 수정했습니다.

2023-07-16 05:42 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +	@Transactional
주석 삭제해도 좋을 것 같아요. 이미 메서드 명으로도 충분히 이해가 됩니다!

2023-07-16 05:43 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +	 */
주석 삭제해도 좋을 것 같아요. 이미 메서드 명으로도 충분히 이해가 됩니다!

2023-07-16 05:45 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +		log.info("create user level: {}, {}", user.getNickname(), newLevel.getName());
개발할 때 확인용으로 생성하신 것 같은데, 삭제해 주세요!

2023-07-16 05:56 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +	public static final String FILE_NAME = "Level1.png";
String 형식으로 하드 코딩하는 방법이 옳은지 잘 모르겠어요.
기획에 변경사항이 생기면 코드 레벨에서 수정해야 하는데, 데이터베이스에서 불러오는 게 조금 더 적합하다고 생각해요.
팀원 분들의 의견이 궁금합니다!

2023-07-16 06:06 UTC, seonghun-dev requested changes

2023-07-16 06:06 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +	@EventListener
상위 트랜잭션이 만료된 이후 비동기적으로 저장하는 로직을 처리해야 하고, 이전 트랜잭션이 만료된 이후 새로운 트랜잭션을 생성해서 실행시켜야 할 것 같습니다

```java
@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
@Transactional(propagation = Propagation.REQUIRES_NEW)
```

2023-07-16 06:06 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/event/UserLevelCreateEvent.java
> +public class UserLevelCreateEvent extends ApplicationEvent {
또한 `CreatEvent`보다 `SetEvent`등으로 처리하면 추후에 재사용에 있어서 유용하게 사용할 수 있을 것 같습니다.
```
@AllArgsConstructor
@Getter
public class UserLevelSetEvent {
     private User user;
     private long userLevelId
}
```

2023-07-16 06:06 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +			eventPublisher.publishEvent(new UserLevelCreateEvent(this, user));
null 일때 먼저 트랜잭션을 던져버리면 user 쪽에 실행 순서나 context switch로 인해서, NullPointException이 발생할수도 있을 것 같습니다

2023-07-16 06:06 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +			eventPublisher.publishEvent(new UserLevelCreateEvent(this, user));
여기서 기본값으로 처리하는 게 좋을 것 같습니다

2023-07-16 06:07 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/event/UserLevelCreateEvent.java
> +public class UserLevelCreateEvent extends ApplicationEvent {
상속이 불필요한 이유가 궁금합니다

2023-07-16 06:08 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +		userRepository.save(user);
User와 UseLevel이 단방향 연관관계로 변경되면, 이 부분도 수정이 되어야 할 것 같습니다

2023-07-16 06:08 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/event/UserLevelCreateEvent.java
> +public class UserLevelCreateEvent extends ApplicationEvent {
https://8iggy.tistory.com/238

2023-07-16 06:09 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +	public static final String FILE_NAME = "Level1.png";
[아래 댓글](https://github.com/depromeet/street-drop-server/pull/218#discussion_r1264612416)로 처리하면 좋을 것 같아요!

2023-07-16 06:23 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +			eventPublisher.publishEvent(new UserLevelCreateEvent(this, user));
이벤트를 발생할 때 트랜젝션 관리에 대한 처리가 필요하므로, [이 로직](https://github.com/depromeet/street-drop-server/pull/218#discussion_r1264613221) 이 필요하군요!

2023-07-16 06:53 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +	 */
삭제했습니다!

2023-07-16 06:54 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +		log.info("create user level: {}, {}", user.getNickname(), newLevel.getName());
반영했습니다. Good!

2023-07-16 06:55 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +		log.info("create user level: {}, {}", user.getNickname(), newLevel.getName());
반영했습니다. Good!

2023-07-16 07:04 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/event/UserLevelCreateEvent.java
> +public class UserLevelCreateEvent extends ApplicationEvent {
반영했습니다. Good!

2023-07-16 07:07 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/UserLevel.java
> +	private List<User> users = new ArrayList<>();
반영했습니다. Good!

2023-07-16 07:13 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +		Optional<UserLevel> userLevel = userLevelRepository.findLevelByUserId(user.getId());
코드 변경

2023-07-16 07:13 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +	@EventListener
## 현재
<img width="444" alt="이벤트 트랜잭션 처리(이전)" src="https://github.com/depromeet/street-drop-server/assets/87802191/7975e8b3-3298-4493-a81f-5c7d8b67c98d">

## 수정
<img width="444" alt="이벤트 트랜잭션 처리(이후)" src="https://github.com/depromeet/street-drop-server/assets/87802191/3add0c48-dd1f-4685-8d2d-51c33ecde25c">

2023-07-16 07:41 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +	@Transactional
수정했습니다

2023-07-16 07:41 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +	@EventListener
수정했습니다

2023-07-16 07:47 UTC, seonghun-dev commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
> +
@Column(name = "level_id")
private Long levelId

2023-07-16 09:21 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
> +
넵 반영했습니다. Good!

2023-07-16 09:43 UTC, siyeonSon approved these changes
너무너무 고생하셨습니다🥹

2023-07-16 09:45 UTC, siyeonSon commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
> +	private UserLevel userLevel;
https://techblog.woowahan.com/2595

2023-07-16 09:47 UTC, siyeonSon commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/UserLevel.java
> +	private Long id;
"level_id" -> "user_level_id"

2023-07-16 09:48 UTC, siyeonSon commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
> +		this.userLevelId = levelId;
`levelId` -> `userLevelId`

2023-07-16 09:48 UTC, siyeonSon commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserService.java
> +    public static final long LEVEL_ID = 1L;
USER_LEVEL_ID

2023-07-16 11:02 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserLevelService.java
> +	private final AwsS3Service awss3Service;
SQL로 처리

2023-07-16 11:03 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/handler/UserLevelCreateEventHandler.java
> +	public static final String FILE_NAME = "Level1.png";
하드코딩된 부분을 제거하고 SQL로 insert 하는 방식으로 수정하였습니다.

2023-07-16 11:03 UTC, siyeonSon commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
> +	private UserLevel userLevel;
저장할 때: `Long userLevelId`
조회할 때: `UserLevel userLevel`

2023-07-16 11:06 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/dto/response/UserLevelResponseDto.java
> +public record UserLevelResponseDto(
@Builder
public record UserLevelResponseDto()

위와 같이 수정하였습니다

2023-07-16 11:07 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/event/UserLevelCreateEvent.java
> +public class UserLevelCreateEvent extends ApplicationEvent {
반영했습니다.

2023-07-16 11:08 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/UserLevel.java
> +	private Long id;
반영했습니다

2023-07-16 11:09 UTC, yunyoung1819 commented on backend/streetdrop-domain/src/main/java/com/depromeet/user/User.java
> +		this.userLevelId = levelId;
반영했습니다

2023-07-16 11:11 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserService.java
> +    public static final long LEVEL_ID = 1L;
수정완료

2023-07-16 11:16 UTC, merged