:sparkles: feat(batch, domain): add User Level Update Schedule
depromeet/street-drop-server pull request #251
Opened 2023-07-20 07:12 UTC by yunyoung1819

2023-07-20 08:05 UTC, siyeonSon commented on backend/streetdrop-batch/src/main/java/com/depromeet/StreetDropBatchApplication.java
> +@EnableBatchProcessing
스케쥴링 어노테이션이 스케쥴링이 돌아가는 `UserLevelBatchScheduler` 에 있거나, 따로 config로 빠지면 좋을 것 같습니다~

2023-07-20 08:14 UTC, seonghun-dev requested changes
고생 많으셨습니다. 
이제 배치서버 있어서 푸시 예약발송등 기능 추가가 쉬워지겠네요
추가 이슈로 배치가 완료되면  배치 처리결과들이 슬랙알림으로 와도 괜찮겠네요

2023-07-20 08:14 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/resources/application-prod.yml
> +      ddl-auto: update
update를 적용하면 안될 것 같습니다

2023-07-20 08:14 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/resources/application-prod.yml
dev 부분도 필요할 것 같습니다.

2023-07-20 08:14 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/resources/application-prod.yml
사실 배치서버는 배포자동화가 필요없을 것 같은데 .gitignore 처리하고 prod는 값 넣어두는 것이 어떨까요?

2023-07-20 08:14 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/resources/application-prod.yml
불필요한 환경변수는 제거하면 좋을 것 같습니다

2023-07-20 08:14 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +					var newLevel = policy.getNewLevel();
정책에 레벨객체를 넣고 다시 id만 빼서 사용하는 이유가 있을까요?

2023-07-20 08:14 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +				new LevelUpdatePolicyImpl(5, getUserLevelById(userLevelRepository, 2L)),
매직넘버보다는 위로 빼서 사용하는게 좋을 것 같은데 이 부분은 정책이라 요구사항정도를 메서드위에 간단하게 주석만 남겨주셔도 좋을 것 같습니다.

2023-07-20 08:14 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +		List<User> allUsers = userRepository.findAll();
삭제여부에 따라서 유저레벨을 변경할지는 논의가 한번 필요하겠네요.

2023-07-20 08:24 UTC, siyeonSon commented on backend/streetdrop-batch/src/main/resources/application-prod.yml
> +  noti-server-url: ${NOTI_SERVER_URL}
불필요한 설정 파일들이 보여요!
DB, slack, notification 외에는 사용하지 않을 것 같아요

2023-07-20 08:24 UTC, siyeonSon commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +		);
기준점이 static final로 빠지면 좋을 것 같아요

2023-07-20 08:25 UTC, siyeonSon commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/level/LevelUpdatePolicy.java
> +public interface LevelUpdatePolicy {
베리베리굿👍

2023-07-20 10:16 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/level/LevelUpdatePolicy.java
> +/**
넵 반영했습니다. 감사합니다 Good!

2023-07-20 10:17 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/level/LevelUpdatePolicy.java
> +public interface LevelUpdatePolicy {
감사합니다.

2023-07-20 10:20 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/resources/application-prod.yml
> +      ddl-auto: update
넵 validate로 변경해두겠습니다. 감사합니다.

2023-07-20 10:24 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/resources/application-prod.yml
> +  noti-server-url: ${NOTI_SERVER_URL}
넵 swagger랑 cloud 쪽 프로퍼티 지우겠습니다. 감사합니다. Good!

2023-07-20 10:39 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/level/LevelUpdatePolicyImpl.java
> +	public LevelUpdatePolicyImpl(int levelCondition, UserLevel userLevel) {
적용했습니다. 감사합니다.

2023-07-21 07:07 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/StreetDropBatchApplication.java
> +@EnableBatchProcessing
넵 위치를 바꾸는건 금방 수정할 수 있는데 혹시 @EnableScheduling 스케쥴링 애노테이션 위치를 스케쥴러 위에 두면 어떤 점이 좋을까여?

2023-07-21 07:10 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +		);
넵 수정했습니다. 리뷰 감사합니다.

2023-07-21 10:57 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/level/LevelUpdatePolicyImpl.java
> +	public boolean isAcceptable(int itemCount) {
아래와 같이 범위 비교로 변경하였습니다. 꼼꼼한 확인 감사합니다.
```
public class LevelUpdatePolicyImpl implements LevelUpdatePolicy {
	private final int minItemDropCount;
	private final int maxItemDropCount;
	private final UserLevel newLevel;

	@Override
	public boolean isAcceptable(int itemCount) {
		return itemCount >= minItemDropCount && itemCount <= maxItemDropCount;
	}
}
```

2023-07-21 11:05 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +			var itemCount = getItemCount(user);
넵 위 쿼리로 조회해서 가져오도록 변경하였습니다. 감사합니다.

2023-07-21 11:06 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +	private void updateUsersLevel(List<User> usersToUpdateLevel) {
조회와 업데이트 로직이 같이 있다보니 코드가 길어져서 가독성 측면에서 나빠지고, 조회와 명령은 따로 분리하는 것이 좋다고 생각했습니다. 🙂

2023-07-21 11:09 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/resources/application-prod.yml
넵 불필요한 환경 변수는 제거하였습니다. prod에 값을 넣어두는거면 application-prod.yml을 로컬에만 두고 원격저장소에 푸시는 빼자는걸로 이해했는데 맞을까요?

2023-07-21 11:15 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +				new LevelUpdatePolicyImpl(5, getUserLevelById(userLevelRepository, 2L)),
넵 감사합니다

2023-07-21 11:22 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +		List<User> allUsers = userRepository.findAll();
넵 이전 배치가 돌기전에 드랍하거나 수정한 유저만 체크하는 것 좋은 것 같습니다!
이 부분이랑 삭제여부는 구현을 어떻게 할지 고민 좀 해보아야할 것 같은데 혹시 따로 이슈로 등록하고 진행해도 괜찮을까요?

2023-07-21 11:24 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +					var newLevel = policy.getNewLevel();
아 해당 메서드의 User.chageLevel을 할때 id가 필요해서 사용 중이었습니다.

2023-07-21 11:33 UTC, siyeonSon commented on backend/streetdrop-batch/src/main/java/com/depromeet/StreetDropBatchApplication.java
> +@EnableBatchProcessing
UserLevelBatchScheduler 클래스 위에 @EnableScheduling 스케쥴링 애노테이션 위에 두면 "아~ 얘가 스케쥴링이 돌아가는 로직이구나~" 를 알 수 있다는 점에서 좋다고 생각했어요

2023-07-21 12:25 UTC, yunyoung1819 commented on backend/streetdrop-batch/src/main/java/com/depromeet/StreetDropBatchApplication.java
> +@EnableBatchProcessing
넵 따로 BatchConfig 만들어서 배치와 스케쥴링 애노테이션 옮겨놓았습니다. 감사합니다.

2023-07-21 13:28 UTC, siyeonSon approved these changes
고생하셨습니다👍

2023-07-21 14:32 UTC, merged