:sparkles: feat(api): add user unblock api
depromeet/street-drop-server pull request #263
Opened 2023-07-23 04:48 UTC by yunyoung1819

- Resolve: #205

2023-07-23 11:37 UTC, seonghun-dev requested changes

2023-07-23 11:37 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserBlockController.java
> +			@RequestParam(value = "blockUserId") Long blockUserId
변경하면 이전버전 IOS에서 호환이 안되어서 우선은 유지해야 될 것 같습니다. 변경하려고 하면 버저닝 해서 기존꺼 유지하면서 다른 API로 추가하고 충분히 업데이트 되면 기존 버전을 없애는 방식으로 처리해야될 것 같습니다

2023-07-23 14:17 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/controller/UserBlockController.java
> +			@RequestParam(value = "blockUserId") Long blockUserId
넵 따로 기능이 변경된 것은 아니여서 버저닝하기보단 파라미터를 기존 이름으로 복원하였습니다.
기존 api 수정 시 버저닝도 계속 고려해야겠군요.
수정 완료했습니다. 감사합니다. Good!

2023-07-24 06:08 UTC, seonghun-dev approved these changes
LGTM

2023-07-27 03:47 UTC, merged