✨ Add Report to Discord Channel
depromeet/street-drop-server pull request #393
Opened 2023-10-29 10:55 UTC by yunyoung1819

- Resolve: #386

2023-10-30 11:24 UTC, seonghun-dev requested changes
추가 테스트 코드에서 외부 API 테스트 할때 `MockServer`를 활용해보는 것도 좋을 것 같습니다.

- Refrence  : https://github.com/spring-projects/spring-framework/issues/19852#issuecomment-453452354

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/test/java/unit/domains/item/service/ItemClaimServiceTest.java
> +//    @Mock
사용하지 않는 코드는 바로바로 제거하는 것이 히스토리 관리에 더 좋을 것 같습니다

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemClaimService.java
> +    private final DiscordItemClaimReportService discordItemClaimReportService;
ItemClaimReportService라는 인터페이스가 있어서 직접 클래스를 사용하는 것이 아닌 DI를 사용하는 것이 좋을 것 같습니다

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemClaimService.java
> +    private final DiscordItemClaimReportService discordItemClaimReportService;
ItemClaimService가 discordReportClaim을 의존하고 있어서 Reporting 채널이 바뀔때 마다 ItemClaimSerive도 변경해주어야 할 것 같습니다

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserBlockService.java
> +
저는 사용자 차단의 경우는 저희 서비스상에서 처리해주거나, 변경이 필요한 부분이 아니기 때문에 크게 필요하지 않을 것이라고 생각했는데, 혹시 사용자 차단 알림을 활용하려고 하시는 부분이 있으실까요?

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordService.java
> +			log.info("**Discord Webhook URl call!!**");
- 로직 테스트용 Log이면 불필요한 부분이라 지워져도 될 것 같습니다.
- 실제 파일 Log를 통해서 분석하고자 하면, 로그 스키마를 논의하고 적용해도 좋을 것 같습니다

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordService.java
> +			restTemplate.postForEntity(webhookUrl, payload, Void.class);
- 결과로 받은 ResponseEnity를 통해서 추후 처리가 있으면 좋을 것 같지만 작업양이 어느정도 있을 것으로 생각 되기 떄문에 추가 이슈로 진행해도 좋을 것 같습니다

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordWebhookPayload.java
> +	public String getContent() {
`@Getter`

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordWebhookPayload.java
> +	public DiscordWebhookPayload(String content) {
`@AllArgsConstructor`

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordService.java
> +	public void sendMessages(String webhookUrl, String content, String discordReportingChannel) {
webhookUrl 부분은 설정으로 빼도 좋을 것 같습니다

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordService.java
> +public class DiscordService {
`implement ItemClaimService`

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordWebhookPayload.java
> +public class DiscordWebhookPayload {
이 부분은 Record 타입을 사용해도 좋을 것 같습니다.

Record에서 아래와 같이 유효성 검사를 진행할 수 있어서, 만약 Content 길이등을 검증하는 용도로 사용할 수 있을 것 같습니다.
```
public record User(
        @NonNull String firstName,
        @NonNull String lastName,
        int age
) {
}
```

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/report/block/service/DiscordUserBlockReportService.java
> +	private String channel;
사용되지 않는 부분인 것 같습니다 DISCORD_REPORTING_CHANNEL이 값이 channel로 사용되는 것 같은데 이 부분 channel로 보내질 수 있도록 수정이 필요할 것 같습니다

2023-10-30 11:24 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/report/block/service/UserBlockReportService.java
> +public interface UserBlockReportService {
상위에서 인터페이스 사용이 안되는 것 같습니다

2023-10-31 13:56 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemClaimService.java
> +        /**
저도 좋은 것 같습니다. 수정하여 반영했습니다 🙂

2023-10-31 14:05 UTC, yunyoung1819 commented on backend/streetdrop-api/src/test/java/unit/domains/item/service/ItemClaimServiceTest.java
> +//    @Mock
넵 좋습니다! 수정하여 반영했습니다

2023-10-31 14:26 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/user/service/UserBlockService.java
> +
음 신고하기의 경우 신고 알림이 있으니까 차단 알림도 같이 있으면 좋겠다고 생각하긴 했었는데 
아직까지 활용 부분은 없을 것 같기는 합니다 🙂

2023-11-05 12:16 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordWebhookPayload.java
> +public class DiscordWebhookPayload {
넵 수정하여 반영하였습니다. 리뷰 감사해요!

2023-11-05 12:22 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordWebhookPayload.java
> +	public DiscordWebhookPayload(String content) {
record 타입으로 변경하여 수정하였습니다!

2023-11-05 12:22 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordWebhookPayload.java
> +	public String getContent() {
record 타입으로 변경하여 수정하였습니다

2023-11-05 12:25 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/domains/item/service/ItemClaimService.java
> +    private final DiscordItemClaimReportService discordItemClaimReportService;
넵 좋은 의견 감사합니다. 수정하였습니다.

2023-11-05 12:29 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/report/block/service/DiscordUserBlockReportService.java
> +	private String channel;
아 그렇네요. 테스트할때 잠시 상수로 뺐었는데 이후 지우지 않고 놓친 것 같습니다.
리뷰 감사합니다.

2023-11-05 12:40 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordService.java
> +	public void sendMessages(String webhookUrl, String content, String discordReportingChannel) {
음 혹시 설정으로 빼는 것이 프로퍼티로 뺴는거 인걸까요~? 
아이템 신고하기와 사용자 차단이 webhook url 이 달라서 DiscordService에서 채널에 따라 url을 분기시키기보다 각각의 Report 서비스에서 webhookUrl을 프로퍼티에서 읽어와 DiscordService로 전달하도록 구현했습니당! 
DiscordService에서 설정으로 빼면 채널별로 url 분기가 필요하지 않나여~?

2023-11-05 12:44 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordService.java
> +	public void sendMessages(String webhookUrl, String content, String discordReportingChannel) {
채널별로 url이 달라지는 군요
그럼 String discordReportingChannel 이 부분이 필요없어지겠군요

2023-11-05 12:47 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordService.java
> +public class DiscordService {
음 `DiscordItemClaimReportService implements ItemClaimReportService` 로 구현하고 있는데 DiscordService가 ItemClaimService를 implement 해야할까여~?

2023-11-05 12:48 UTC, seonghun-dev commented on backend/streetdrop-api/src/main/java/com/depromeet/external/discord/DiscordService.java
> +public class DiscordService {
앗, DiscordItemClaimReportService 인 줄 알았네요

2023-11-05 12:49 UTC, yunyoung1819 commented on backend/streetdrop-api/src/main/java/com/depromeet/report/block/service/UserBlockReportService.java
> +public interface UserBlockReportService {
아 `DiscordUserBlockReportService implements UserBlockReportService`로 사용하고 있는데 혹시 상위에서 인터페이스 사용이 안된다는건 어떤 부분 말씀이실까여~?

2023-11-14 12:35 UTC, merged