:recycle: refactor: update user level batch refactoring
depromeet/street-drop-server pull request #454
Opened 2024-03-25 07:56 UTC by seonghun-dev

2024-03-25 08:02 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +		var itemUpdateUsers = itemRepository.findAllItemUpdateUser(LocalDateTime.now().minusMinutes(30)).stream().distinct().toList();
최근에 아이템 드랍된거를 기준으로 가져옴

2024-04-03 10:03 UTC, siyeonSon requested changes

2024-04-03 10:03 UTC, siyeonSon commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/item/repository/ItemRepository.java
> +
QueryDSL로 변경하는 건 어떤가요? 리팩터링 할 때 `com.depromeet.domains.item.dto.UserItemCount` 도 신경써야 해서 꽤나 번거롭읍니다 😭

2024-04-07 06:15 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/level/LevelUpdater.java
> +				.orElse(LevelPolicy.LEVEL_1);
부등호가 잘못 되었네요. dropCountStart만 남기고 그 이상 되면 올리는 경우로만 처리하도록 하겠습니다. 감사합니다.

2024-04-07 06:16 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/item/repository/ItemRepository.java
> +
좀 길어질 것 같아서 queryDSL로 풀어서 해결해보겠습니다.

2024-05-09 07:54 UTC, siyeonSon commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/user/service/UserService.java
> +							.orElse(null);
null을 던졌다가 LevelUpdater에서 NPE가 발생할 수 있을 것 같아요

2024-05-09 07:56 UTC, siyeonSon commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/level/LevelUpdater.java
> +	}
이 문제가 해결이 되지 않아요 ㅠㅠ
- dropCount가 51개인 경우
  - return: LEVEL_1
  - answer: LEVEL_3

2024-05-09 07:58 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/item/repository/ItemRepository.java
> +
유저별로 아이템 개수를 세는 테이블을 하나 만들어둘 생각이라서, 추후에 고민해보고 변경해보곘습니다

2024-05-09 07:58 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/level/LevelUpdater.java
> +	}
end를 날려버리곘습니다.

2024-05-09 07:58 UTC, seonghun-dev commented on backend/streetdrop-batch/src/main/java/com/depromeet/domains/level/LevelUpdater.java
> +	}
추후에 어드민에서 수정할 수 있게끔 디비에 넣어서 변경해두겠습니다.

2024-05-10 06:00 UTC, merged