:white_check_mark: test: Add ItemController Test Code
depromeet/street-drop-server pull request #63
Opened 2023-05-26 13:09 UTC by yunyoung1819

Resolve: #45

2023-05-27 07:47 UTC, siyeonSon approved these changes
추후에 ItemSerivce Test도 PR 올려주시면 좋을 것 같아요! 고생하셨습니다😀

2023-05-28 08:21 UTC, seonghun-dev requested changes

2023-05-28 08:21 UTC, seonghun-dev commented on src/test/java/com/depromeet/streetdrop/apis/item/controller/ItemControllerTest.java
> +    @DisplayName("[POST] 아이템 드랍 저장")
저장 로직에서 Validation에 대한 테스트가 있으면 좋을 것 같습니다

2023-05-30 09:51 UTC, yunyoung1819 commented on src/test/java/com/depromeet/streetdrop/apis/item/controller/ItemControllerTest.java
> +    @DisplayName("[POST] 아이템 드랍 저장")
넵 validation 테스트도 추가하겠습니다

2023-06-02 11:45 UTC, seonghun-dev approved these changes
좋습니다. 😄 
감사합니다

2023-06-02 12:59 UTC, merged