:sparkles: feat: add item like/unlike
depromeet/street-drop-server pull request #74
Opened 2023-06-03 11:03 UTC by yunyoung1819

Resolve: #72 
- 아이템에 대한 좋아요 기능
- 좋아요를 이미 눌렀을 시에 대한 중복 체크 기능
- 아이템에 대한 좋아요 취소 기능

2023-06-04 14:33 UTC, siyeonSon commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +		if (itemOptional.isPresent()) {
코드 재사용성을 높히기 위해 **itemId으로 Item을 찾는 로직을 ItemService에 public 메서드로 선언**하면 좋을 것 같습니다!
itemId으로 Item을 찾는 로직을 다른 로직에서도 사용할 것 같아요. 예를 들어 아래 좋아요 취소 로직이나 아이템에서 특정 정보를 조회하는 로직 등이 있어요.

```
public Item getItem(Long itemId) {
    return itemRepository.findById(itemId)
            .orElseThrow(() -> new NotFoundException(ErrorCode.NOT_FOUND));
}
```

2023-06-04 14:33 UTC, siyeonSon commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +		if (itemOptional.isPresent()) {
그리고 코드의 가독성이 좋아질 것 같아요.
```
@Transactional
public ItemLikeResponseDto likeItem(Long itemId, User user) {
    var item = getItem(itemId);

    checkUserAlreadyLike(user, item);

    var itemLike = ItemLike.builder()
			    .item(item)
			    .user(user)
			    .build();

    itemLikeRepository.save(itemLike);

    return new ItemLikeResponseDto(itemLike);
}
```

2023-06-04 14:33 UTC, siyeonSon commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +			throw new IllegalArgumentException("User has already liked the item");
**enum으로 선언된 ErrorCode**에서 커스텀 에러들이 관리되면 좋을 것 같아요. 에러 코드들을 한 눈에 볼 수 있고, 관리할 수 있는 장점이 있을 것 같아요.

2023-06-04 14:33 UTC, siyeonSon commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +			var item = itemOptional.get();
위 댓글처럼 `var item = getItem(itemId);` 로 Item 정보를 가져오면 코드가 깔끔해질 것 같아요

2023-06-04 14:33 UTC, siyeonSon commented on src/main/java/com/depromeet/streetdrop/apis/item/controller/ItemController.java
> +	}
좋아요 관련 기능들은 ItemLikeController에서 관리되면 좋을 것 같습니다. 코드의 모듈화와 유지 보수성을 향상시킬 수 있을 것 같아요!

Item CRUD 기능과 Item 좋아요 기능은 서로 독립적이라고 생각해요. 
`ItemLikeController`는 좋아요와 관련된 기능들을 담당하고, `ItemController`는 Item CURD 기능들을 담당하는 구조로 분리하면 좋을 것 같아요.

2023-06-04 14:36 UTC, siyeonSon commented
discuss label을 추가하셨는데, 혹시 논의하면 좋은 사항이 있으실까요?!

2023-06-05 08:55 UTC, seonghun-dev requested changes

2023-06-05 08:55 UTC, seonghun-dev commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +			throw new IllegalArgumentException("User has already liked the item");
IllegalArgumentException은 잘못된 인자를 넘겼을 때 발생하는 예외라서, 이 부분은 "한번 좋아요한 게시글은 다시 좋아요 할 수 없다"  이러한 비즈니스적 로직에 대해서 문제가 발생하는 것이기 때문에 Businesss Exception으로 넘겨서 처리하는 것이 좋을 것 같습니다.

2023-06-05 08:55 UTC, seonghun-dev commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +		Optional<Item> itemOptional = itemRepository.findById(itemId);
ItemRepository에서 Item 여부를 조회할 필요가 있을까요?
Item like테이블에 item id 정보와 user 정보를 모두 가지고 있어서 해당 부분만 확인해도 큰 문제가 발생하지 않을 것 같습니다

2023-06-05 08:55 UTC, seonghun-dev commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +		if (item.getLikes().stream().anyMatch(like -> like.getUser().getId().equals(user.getId()))) {
item.getLikes()하게되면 아래와 같은 쿼리가 날라가게 되는데 이렇게 디비에서는 item_id에 대해서만 조회하고, 서버에서 userId로 비교할 필요가 있을까요?

```sql
select l1_0.item_id,l1_0.item_like_id,l1_0.created_at,l1_0.modified_at,l1_0.user_id from item_like l1_0 where l1_0.item_id=?
````

2023-06-05 08:55 UTC, seonghun-dev commented on src/main/java/com/depromeet/streetdrop/domains/item/entity/Item.java
> +	public int getItemLikeCount() {
count 전략에 대해서도 추후 생각해보면 좋을 것 같습니다

2023-06-05 09:11 UTC, siyeonSon commented on src/main/java/com/depromeet/streetdrop/domains/item/entity/Item.java
> +	public int getItemLikeCount() {
`@LazyCollection(LazyCollectionOption.EXTRA)` 어노테이션을 사용해서 지연로딩으로 가져와도 좋을 것 같아요

2023-06-05 09:13 UTC, siyeonSon commented on src/main/java/com/depromeet/streetdrop/apis/item/controller/ItemController.java
> +	@DeleteMapping("/{itemId}/unlikes")
Post `/{itemId}/likes`  -> 좋아요 할 떄
Delete `/{itemId}/likes`  -> 좋아요 취소
맞을까요?!

2023-06-06 10:13 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/apis/item/controller/ItemController.java
> +	@DeleteMapping("/{itemId}/unlikes")
좋아요 누를 때
post: /{itemId}/likes
좋아요 취소를 누를때 
post: {itemId}/unlikes

2023-06-06 10:49 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +			var item = itemOptional.get();
음 해당 메서드가 @Transaction이 선언된 메서드라서 getItem(itemId)와 같이 inner 함수를 호출하면 트랜잭션이 정상 동작하지 않아서 고민해볼 부분인 것 같아요. 
트랜잭션의 프록시 패턴에 대해서 잘 정리된 링크가 있어 공유드립니다. 
리뷰 감사합니다ㅎㅎ

- https://steady-coding.tistory.com/610
- https://velog.io/@chullll/Transactional-%EA%B3%BC-PROXY

2023-06-06 11:00 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/apis/item/controller/ItemController.java
> +		} catch (NotFoundException e) {
Controller 단에서 try /catch를 제외하였습니다.

2023-06-06 11:26 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/apis/item/controller/ItemController.java
> +		}
넵 아이템에 대한 좋아요를 눌렸을 경우 해당 아이템이 삭제되거나 존재하지 없는 경우에는 클라이언트로 404를 리턴해주려는 의도였는데 서비스 단에서 이미 예외를 처리해서 클라이언트로 exception을 전달해주므로 컨트롤러 부분에서는 제거해야 할 것 같습니다.

2023-06-06 13:29 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/apis/item/controller/ItemController.java
> +			return ResponseEntity.notFound().build();
unlike는 204를 리턴하고 클라이언트와 협의하여 추후 리팩토링 진행

2023-06-06 13:51 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/common/dto/ResponseDto.java
> +	public static ResponseEntity<Void> notFound() {
넵 해당 부분 제거하고 not found는 따로 비즈니스 예외로 처리하는 식으로 수정하였습니다.

2023-06-06 13:55 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/item/dto/response/ItemLikeResponseDto.java
> +public record ItemLikeResponseDto (
아이템 좋아요 개수를 전달하도록 수정하였습니다.

2023-06-06 13:56 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/apis/item/controller/ItemController.java
> +			return ResponseEntity.notFound().build();
우선 204로 리턴하고 추후 클라이언트와 논의하여 수정하기로 협의

2023-06-06 14:00 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/item/dto/response/ItemLikeResponseDto.java
> +				new UserResponseDto(itemLike.getUser()),
아 그렇네요. 나중에 유저를 추가하면서 불필요하게 ItemLike에서 꺼내오고 있었네요. 수정했습니다.

2023-06-06 14:04 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +			if (itemLike != null) {
넵 수정하였습니다.

2023-06-06 14:04 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +			throw new IllegalArgumentException("User has already liked the item");
넵 수정하였습니다.

2023-06-06 14:37 UTC, siyeonSon approved these changes

2023-06-06 14:37 UTC, seonghun-dev requested changes

2023-06-06 14:37 UTC, seonghun-dev commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +			throw new AlreadyItemLikedException();
BusinessException(ErrorCode.Arlready~~)

2023-06-06 14:37 UTC, seonghun-dev commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +		Optional<ItemLike> itemLikeOptional = itemLikeRepository.findByItemIdAndUser(itemId, user);
itemLikeRepository.findByItemIdAndUser(itemId, user)
            .ifPresent(itemLikeRepository::delete);

2023-06-09 08:02 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +			throw new AlreadyItemLikedException();
private void checkUserAlreadyLike(User user, Item item) {
	boolean alreadyLiked = itemLikeRepository.existsByUserIdAndItemId(user.getId(), item.getId());
	if (alreadyLiked) {
		throw new BusinessException(ErrorCode.ALREADY_ITEM_LIKED_ERROR);
	}
}
	
위와 같이 수정했습니다.

2023-06-09 08:04 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/item/service/ItemLikeService.java
> +		Optional<ItemLike> itemLikeOptional = itemLikeRepository.findByItemIdAndUser(itemId, user);
넵 수정해서 반영했습니다.

2023-06-09 14:22 UTC, seonghun-dev approved these changes
Lgtm 😃

2023-06-09 15:15 UTC, merged