:sparkles: feat: Add admin All User search API
depromeet/street-drop-server pull request #77
Opened 2023-06-06 05:56 UTC by yunyoung1819

Resolve: #75

2023-06-16 10:40 UTC, seonghun-dev requested changes

2023-06-23 07:37 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/admin/service/AdminService.java
> +				.collect(Collectors.toList());
수정했습니다.

2023-06-23 07:38 UTC, yunyoung1819 commented on src/main/java/com/depromeet/streetdrop/domains/admin/service/AdminService.java
> +	public Page<User> findAll(Pageable pageable) {
수정했습니다.

2023-06-23 08:49 UTC, yunyoung1819 commented
프로젝트 구조 변경으로 인해 다시 checkout 해서 PR 생성하고 작업 진행

2023-06-23 08:49 UTC, closed without merging